[discovery]
host = "gc-kg-db-do-user-7802184-0.b.db.ondigitalocean.com"
user = "user_gc_prod"
password = "must!123@"
port = 25060
database = "gc_prod"

[sheets]
type = "service_account"
project_id = "data-team-451307"
private_key_id = "bf257cc142748cd956d9b582eeabfe73bbe28193"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCe4zmKJpFk4r+c
CCDCiehyWUVCUisT1vLHIZuV/yOmQMlEfr/3YvtgbvFUtFUsgqVTLmkHcE0mkOHC
DOacgEt1HxY5tNJIr6r1z7X7namId4F/qRoR8BrCQto8yCv0AJBd8tazU0QCOmfB
c1W+2P6N1BkBFnw1pyVJ381AETmpt5MazAKdgfr4gGE9+cbo48aqz9w1MesewW35
qerSK2AkmjQblBOZXxWqJlPcRPv/QlAVec9QA4DkmKwAvXlRSc877xf8JdCJE2wn
KG+OTsaZ+NOS5Hnw5asn1g53AQIRTk2H48FzSLcByLWiO7ZtBPil8l3/P4uqRCXb
PayIuJmrAgMBAAECggEAQXPecLRJodMs1sScZjd0a6Ktvs/lkgMyuOh11PkpQOQg
ZViHkQwT/NpHDTtKeQ8KtvT/7EINbi0x6wPwfhj1vLZFLBl6pNnE5gUedRwyShbc
4G+TXz9Xbp4mk/Jr9NTEpAcU/gN3mSlhM5ZlBL0UQ+3TLRkLqviDimapAVL3O5vP
TPQxR/8dY8ACvqIWCAIlD10Vwb+K9y2COTw/NSv5051urynQ2DUtUcSm3fBvNCzs
vnw/RxhYmu84iiND9tNCTlTfEyuGt4G1YMbCwn6Xcc+cxi0uq/QVTEM1OI6BCq0J
PCNmqPu1bouE7bR5Fh6WaE77RQMzrvnu0hxj6uSgIQKBgQDM1AUPsLW7gSozPbPB
TSvrB6TqI5+A2R7B/8cRGMqMImj2g3n5st7QMkikWiCp2++ZSIBl016G2K2EMFAD
uBUwpyGQ0KQs45hea6XpHVuyly5FqEzgZd6cepczJRxjuA7vA4UKS+QZvrPSPh8D
FIqG7lMRR06p/a3iowoRQG6kCwKBgQDGlQfHEAL2U0RFtdkcV2HEWAhshUqz57ol
c8qoIwxDtbvO59k94/WnOiVDCyUXoXrc9poWkK3zLIZ7R3w1TW4NiJLbVvfETafg
urUQ1+L97qGVw9kBe5BtBxYKQUv5r4ztIBe97OXIp9iqgRdUrq5HfknJelzemaZL
X7tGcObE4QKBgFsrqFESk+GxHYqPVVqeMgU8ctBxKMceXY12fzIB+e4kRtorLXjS
gFDlgOX+4/kXV2/AEL7CNZoKCjoDkyoEnxH34n3mEJ2WdLTab4/yrGUy27rPreBY
F51JB9IRG7DbNXJ3+5jYrOA0vS/AzOb/FqX2oOzY84/AxcxSS+Hf7x9/AoGBAJIq
M5VTtbp1Q3VEClAQCUgpu9mUqo2M7LiQaAQl9+sGovwCLyac2b2C0NZuJ5kjJHnr
kTM2vrKUfU/UKBpbqbuQYPfNJYV52y1Qf+Gr5coekRTZGKs8tetqIdDeivt3OXV3
/8Gt0txEnvexGOkdwe2hiNIhnKXD1mD4T7HjfBhBAoGADGrpFhys6R5ki5Rf0MJo
LrqYCl8GCcPvp/QCKG6lj0eXYWS1wmhFNffysTWZLD5z3DuYrcpA2LCmGA8M0G6h
/etIChC6LaqXAz4Z4KQ/khDTNM4xHZUFmKGAg6drAx/GmTZUrAuGJrMeYHVBs6Zk
Dx1xXvgj3qERn/o80Itvf98=
-----END PRIVATE KEY-----"""
client_email = "data101@data-team-451307.iam.gserviceaccount.com"
client_id = "103064373485072818881"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/data101%40data-team-451307.iam.gserviceaccount.com"
universe_domain = "googleapis.com"